name: Release
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Test
        uses: ./
        continue-on-error: true
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: npm install jfslajfslkd
      - name: Release
        run: npx semantic-release # this only runs on master and develop. see .releaserc.js
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
